"""Initial migration

Revision ID: d8dadb0f190c
Revises: 
Create Date: 2025-08-15 18:46:20.011047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dadb0f190c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('contacto_principal', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permisos_categoria'), ['categoria'], unique=False)

    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_base', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('puede_crear_tecnicos', sa.Boolean(), nullable=True),
    sa.Column('puede_editar_tecnicos', sa.Boolean(), nullable=True),
    sa.Column('puede_eliminar_tecnicos', sa.Boolean(), nullable=True),
    sa.Column('puede_ver_todos_los_clientes', sa.Boolean(), nullable=True),
    sa.Column('puede_ver_todos_los_equipos', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol', 'permiso_id', name='uq_rol_permiso'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('roles_permisos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_permisos_rol'), ['rol'], unique=False)

    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_problema', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('superadmins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puede_crear_administradores', sa.Boolean(), nullable=True),
    sa.Column('puede_eliminar_administradores', sa.Boolean(), nullable=True),
    sa.Column('puede_ver_todos_los_datos', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('habilidades', sa.Text(), nullable=True),
    sa.Column('nivel_experiencia', sa.String(length=20), nullable=True),
    sa.Column('contacto_emergencia_nombre', sa.String(length=100), nullable=True),
    sa.Column('contacto_emergencia_telefono', sa.String(length=20), nullable=True),
    sa.Column('contacto_emergencia_parentesco', sa.String(length=50), nullable=True),
    sa.Column('numero_identificacion', sa.String(length=50), nullable=True),
    sa.Column('tipo_licencia', sa.String(length=20), nullable=True),
    sa.Column('vencimiento_licencia', sa.Date(), nullable=True),
    sa.Column('seguro_social', sa.String(length=50), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_ultima_evaluacion', sa.Date(), nullable=True),
    sa.Column('calificacion_evaluacion', sa.Float(), nullable=True),
    sa.Column('ubicacion_actual', sa.String(length=200), nullable=True),
    sa.Column('ultima_ubicacion_conocida', sa.String(length=200), nullable=True),
    sa.Column('ultima_actualizacion_ubicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('asignado_por', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'permiso_id', name='uq_usuario_permiso'),
    sqlite_autoincrement=True
    )
    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('tiempo_estimado', sa.Integer(), nullable=True),
    sa.Column('tiempo_real', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('codigo_inventario', sa.String(length=50), nullable=True, comment='Código de inventario interno'),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment="Tipo de equipo: 'impresora', 'multifuncional', 'escaner', 'fax'"),
    sa.Column('area', sa.String(length=100), nullable=True, comment='Área o departamento donde está ubicado el equipo'),
    sa.Column('ubicacion_detalle', sa.Text(), nullable=True, comment='Detalles específicos de la ubicación'),
    sa.Column('propiedad', sa.String(length=20), nullable=False, comment="Propiedad: 'ecoloimp' o 'cliente'"),
    sa.Column('estado', sa.String(length=20), nullable=False, comment="Estado: 'activo', 'inactivo', 'mantenimiento', 'baja'"),
    sa.Column('ultimo_conteo_impresiones', sa.BigInteger(), nullable=True),
    sa.Column('ultimo_conteo_escaneos', sa.BigInteger(), nullable=True),
    sa.Column('ultimo_conteo_copias', sa.BigInteger(), nullable=True),
    sa.Column('ultimo_conteo_fecha', sa.DateTime(), nullable=True, comment='Fecha del último conteo registrado'),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True, comment='Fecha de instalación del equipo'),
    sa.Column('fecha_ultimo_mantenimiento', sa.Date(), nullable=True),
    sa.Column('fecha_proximo_mantenimiento', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('color', sa.Boolean(), nullable=True, comment='¿Es una impresora a color?'),
    sa.Column('velocidad_impresion', sa.String(length=50), nullable=True, comment='Ej: 30 ppm'),
    sa.Column('resolucion', sa.String(length=50), nullable=True, comment='Ej: 1200x1200 dpi'),
    sa.Column('conexiones', sa.String(length=100), nullable=True, comment='Tipos de conexión: USB, Ethernet, WiFi'),
    sa.Column('modelo_toner', sa.String(length=100), nullable=True, comment='Modelo de tóner o tinta compatible'),
    sa.Column('modelo_tambor', sa.String(length=100), nullable=True, comment='Modelo de tambor compatible'),
    sa.Column('capacidad_hojas', sa.Integer(), nullable=True, comment='Capacidad del alimentador de hojas'),
    sa.Column('numero_activo_fijo', sa.String(length=50), nullable=True, comment='Número de activo fijo del cliente'),
    sa.Column('garantia_hasta', sa.Date(), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_codigo_inventario'), ['codigo_inventario'], unique=True)
        batch_op.create_index(batch_op.f('ix_equipos_modelo'), ['modelo'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_numero_serie'), ['numero_serie'], unique=True)
        batch_op.create_index(batch_op.f('ix_equipos_sucursal_id'), ['sucursal_id'], unique=False)

    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('impuestos', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_visita', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('tipo_visita', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_conteo', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('contador_impresion_actual', sa.BigInteger(), nullable=False),
    sa.Column('contador_escaneo_actual', sa.BigInteger(), nullable=False),
    sa.Column('contador_copias_actual', sa.BigInteger(), nullable=False),
    sa.Column('contador_impresion_anterior', sa.BigInteger(), nullable=True),
    sa.Column('contador_escaneo_anterior', sa.BigInteger(), nullable=True),
    sa.Column('contador_copias_anterior', sa.BigInteger(), nullable=True),
    sa.Column('diferencia_impresiones', sa.BigInteger(), nullable=True),
    sa.Column('diferencia_escaneos', sa.BigInteger(), nullable=True),
    sa.Column('diferencia_copias', sa.BigInteger(), nullable=True),
    sa.Column('estado_equipo', sa.String(length=20), nullable=False),
    sa.Column('requiere_mantenimiento', sa.Boolean(), nullable=True),
    sa.Column('problemas_detectados', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conteos', schema=None) as batch_op:
        batch_op.create_index('idx_conteo_equipo_fecha', ['equipo_id', 'fecha_conteo'], unique=False)
        batch_op.create_index('idx_conteo_tecnico_fecha', ['tecnico_id', 'fecha_conteo'], unique=False)
        batch_op.create_index(batch_op.f('ix_conteos_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conteos_fecha_conteo'), ['fecha_conteo'], unique=False)
        batch_op.create_index(batch_op.f('ix_conteos_tecnico_id'), ['tecnico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conteos_visita_id'), ['visita_id'], unique=False)

    op.create_table('pedidos_piezas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('parte_id', sa.Integer(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
    sa.Column('cantidad_aprobada', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('urgencia', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('observaciones_admin', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ),
    sa.ForeignKeyConstraint(['parte_id'], ['partes.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('trabajo_realizado', sa.Text(), nullable=False),
    sa.Column('problemas_encontrados', sa.Text(), nullable=True),
    sa.Column('solucion_aplicada', sa.Text(), nullable=True),
    sa.Column('recomendaciones', sa.Text(), nullable=True),
    sa.Column('piezas_utilizadas', sa.Text(), nullable=True),
    sa.Column('estado_inicial', sa.String(length=50), nullable=True),
    sa.Column('estado_final', sa.String(length=50), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_fin', sa.DateTime(), nullable=True),
    sa.Column('tiempo_total', sa.Integer(), nullable=True),
    sa.Column('cliente_satisfecho', sa.Boolean(), nullable=True),
    sa.Column('observaciones_cliente', sa.Text(), nullable=True),
    sa.Column('firma_cliente', sa.Text(), nullable=True),
    sa.Column('nombre_firma', sa.String(length=100), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('aprobado_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes')
    op.drop_table('pedidos_piezas')
    with op.batch_alter_table('conteos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conteos_visita_id'))
        batch_op.drop_index(batch_op.f('ix_conteos_tecnico_id'))
        batch_op.drop_index(batch_op.f('ix_conteos_fecha_conteo'))
        batch_op.drop_index(batch_op.f('ix_conteos_equipo_id'))
        batch_op.drop_index('idx_conteo_tecnico_fecha')
        batch_op.drop_index('idx_conteo_equipo_fecha')

    op.drop_table('conteos')
    op.drop_table('visitas')
    op.drop_table('facturas')
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipos_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_equipos_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_equipos_modelo'))
        batch_op.drop_index(batch_op.f('ix_equipos_codigo_inventario'))
        batch_op.drop_index(batch_op.f('ix_equipos_cliente_id'))

    op.drop_table('equipos')
    op.drop_table('asignaciones')
    op.drop_table('usuarios_permisos')
    op.drop_table('tecnicos')
    op.drop_table('superadmins')
    op.drop_table('sucursales')
    op.drop_table('solicitudes')
    with op.batch_alter_table('roles_permisos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_permisos_rol'))

    op.drop_table('roles_permisos')
    op.drop_table('admins')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('servicios')
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permisos_categoria'))

    op.drop_table('permisos')
    op.drop_table('partes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
